title: F2F Project Docs
description: Project Documentation
theme: just-the-docs

url: https://bestleaks.github.io/f2f-projects-docs

aux_links:
  Feedback: https://github.com/BestLeaks/Fears-to-Fathom-Best-Projects
  F2F Discord: https://discord.gg/fears-to-fathom

# not working
#  nav_external_links:
#  - title: Docs Feedback
#    url: https://github.com/BestLeaks/Fears-to-Fathom-Best-Projects

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/BestLeaks/f2f-projects-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

footer_content: "Copyright &copy; Best"

