title: F2F Project Docs
description: Project Documentation
theme: just-the-docs

url: https://bestleaks.github.io/f2f-projects-docs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
